### ISSUE TITLE
Geocode addresses in Google Sheets

### ISSUE THREAD

**Issue by lesserj** [clubkemp/sheets2map#4]
You can have addresses entered into a Google Sheet automatically geocode a latitude and longitude.  Adding this capability may make it even easier for users to enter data.  See https://www.guguweb.com/2020/01/24/geocode-addresses-with-google-sheets-and-google-geocoding-api/

**Comment by clubkemp** [comment]
Added a script to generate lat/longs off address triggered on spreadsheet change
